<?php
/**
 * "Still on-hold" reminder email — sent 24 hours after an order is placed,
 * ONLY if the order is still sitting on-hold (unpaid) at that point. If the
 * customer has already paid (order moved to processing/completed) or the
 * order was cancelled in that time, nothing is sent.
 *
 * Registers as a real WooCommerce email under WooCommerce -> Settings ->
 * Emails, named "On-Hold Reminder (24hr)" — so it can be toggled on/off and
 * its subject/recipient edited from the normal WC admin screen, same as
 * every built-in WC email. The BODY content (the order-recap template) is
 * generated by anvil_on_hold_reminder_body() below; edit the strings in
 * that function to change the copy.
 *
 * Was originally spec'd as a 1-hour reminder with automatic status update
 * (on-hold -> processing) once a card-via-invoice payment came in. Checked
 * the live store's enabled WooCommerce payment gateways directly
 * (GET /wp-json/wc/v3/payment_gateways) — the "Pay With Credit Card Via
 * Invoice" option is WooCommerce's own core "bacs" (Direct Bank Transfer)
 * gateway, just relabeled; there's no actual card processor (Stripe/Square/
 * etc.) wired behind it, only Bankful for the Ethereum option (which already
 * auto-confirms on its own). bacs has no payment signal to hook into, so
 * there's nothing to detect automatically — confirming paid orders still
 * has to be a manual status change, same as Zelle/CashApp. Delay bumped to
 * 24 hours instead of 1 to match.
 *
 * How the 24-hour delay works: WordPress has no built-in "wait N hours then
 * check a condition" primitive, so this uses WP-Cron's wp_schedule_single_event
 * — fires once, 24 hours out, and the callback re-checks the order's current
 * status before sending anything.
 *
 * Setup:
 * 1. Paste into Code Snippets (Snippets -> Add New), run everywhere, activate.
 * 2. Go to WooCommerce -> Settings -> Emails -> "On-Hold Reminder (24hr)" and
 *    confirm it's enabled (it defaults to enabled).
 * 3. Place a test order and either wait 24 hours or use a plugin like WP Crontrol
 *    to fire the scheduled anvil_send_on_hold_reminder event early, to see the
 *    real email.
 *
 * WP-Cron caveat: WP-Cron only runs on site traffic by default. If this
 * store gets long stretches with zero visitors, the 24-hour event can fire
 * late (whenever the next visitor arrives). If reminders need to be exactly
 * on time, ask about wiring a real server cron hitting wp-cron.php every
 * few minutes — flagging this rather than assuming it matters.
 */

// ─── 1. Schedule the check when an order is created on-hold ───────────────

add_action('woocommerce_new_order', function ($order_id, $order = null) {
    if (!$order) {
        $order = wc_get_order($order_id);
    }
    if (!$order || $order->get_status() !== 'on-hold') {
        return;
    }
    if ($order->get_meta('_anvil_reminder_scheduled') === 'yes') {
        return;
    }
    $order->update_meta_data('_anvil_reminder_scheduled', 'yes');
    $order->save();

    wp_schedule_single_event(time() + DAY_IN_SECONDS, 'anvil_send_on_hold_reminder', [$order_id]);
}, 10, 2);

add_action('anvil_send_on_hold_reminder', function ($order_id) {
    $order = wc_get_order($order_id);
    if (!$order || $order->get_status() !== 'on-hold') {
        return; // paid, cancelled, etc. in the last hour — say nothing
    }

    WC()->mailer(); // ensures WC_Emails is loaded so our class below is registered
    $email = WC()->mailer()->get_emails()['Anvil_On_Hold_Reminder_Email'] ?? null;
    if ($email) {
        $email->trigger($order_id, $order);
    }
}, 10, 1);

// ─── 2. The email itself — a normal WooCommerce email class ───────────────

add_filter('woocommerce_email_classes', function ($email_classes) {
    if (!class_exists('WC_Email')) {
        return $email_classes;
    }

    class Anvil_On_Hold_Reminder_Email extends WC_Email {
        public function __construct() {
            $this->id             = 'anvil_on_hold_reminder';
            $this->title          = 'On-Hold Reminder (24hr)';
            $this->description    = 'Sent 24 hours after an order is placed, only if it is still On-Hold (unpaid).';
            $this->customer_email = true;
            $this->heading        = 'Your order is on hold';
            $this->subject        = 'Order #{order_number} is placed — nothing has been charged yet';
            $this->template_html  = null; // body is built directly in get_content_html()

            parent::__construct();
        }

        public function trigger($order_id, $order = false) {
            $this->object = $order ?: wc_get_order($order_id);
            if (!$this->object) {
                return;
            }
            $this->recipient = $this->object->get_billing_email();
            if (!$this->is_enabled() || !$this->get_recipient()) {
                return;
            }
            $this->send($this->get_recipient(), $this->get_subject(), $this->get_content(), $this->get_headers(), $this->get_attachments());
        }

        public function get_content_html() {
            return anvil_on_hold_reminder_body($this->object);
        }
    }

    $email_classes['Anvil_On_Hold_Reminder_Email'] = new Anvil_On_Hold_Reminder_Email();
    return $email_classes;
});

// ─── 3. Body template — pulls real order data (line items, BOGO/volume
//        discount fee lines, shipping, total) so nothing here is hardcoded
//        except the evergreen "chk10" incentive code and the support email ───

function anvil_on_hold_reminder_body($order) {
    $first_name = esc_html($order->get_billing_first_name());
    $order_number = esc_html($order->get_order_number());

    $lines = '';
    foreach ($order->get_items() as $item) {
        $name = esc_html($item->get_name());
        $qty = $item->get_quantity();
        $unit_price = $qty > 0 ? $item->get_total() / $qty : 0;
        $line_total = $item->get_total();
        $lines .= sprintf(
            '<tr><td>Lot %s $%s x %d</td><td style="text-align:right">$%s</td></tr>',
            $name,
            number_format((float) $unit_price, 2),
            $qty,
            number_format((float) $line_total, 2)
        );
    }

    // Any fee line with a negative total is a discount (BOGO, Volume
    // Discount, payment-method discount — see lib/bogoDiscount.ts,
    // volumeDiscount.ts, place-order/route.ts). Shown generically so this
    // stays correct if new discount types are added later.
    foreach ($order->get_items('fee') as $fee) {
        $total = (float) $fee->get_total();
        if ($total >= 0) {
            continue;
        }
        $lines .= sprintf(
            '<tr><td>%s applied</td><td style="text-align:right">-$%s</td></tr>',
            esc_html($fee->get_name()),
            number_format(abs($total), 2)
        );
    }

    $shipping_total = (float) $order->get_shipping_total();
    $lines .= sprintf(
        '<tr><td>Ground Shipping</td><td style="text-align:right">$%s</td></tr>',
        number_format($shipping_total, 2)
    );

    $total = (float) $order->get_total();

    ob_start();
    ?>
    <div style="font-family:sans-serif;max-width:520px;margin:0 auto;">
      <p><strong>Order #<?php echo $order_number; ?> is placed. Nothing has been charged.</strong></p>

      <p>Hi there <?php echo $first_name; ?>! You've got an order set up with us but haven't completed it yet.</p>

      <p>If the payment step gave you pause, here's the whole process:</p>
      <ol>
        <li>Place your order — Nothing charged</li>
        <li>Check your email — Secure link, 15 minutes</li>
        <li>Pay With Credit Card Via Invoice — Ships same or next business day</li>
      </ol>

      <table style="width:100%;border-collapse:collapse;margin:16px 0;">
        <tr><td colspan="2"><strong>Order #<?php echo $order_number; ?></strong></td></tr>
        <?php echo $lines; ?>
        <tr><td><strong>Total</strong></td><td style="text-align:right"><strong>$<?php echo number_format($total, 2); ?></strong></td></tr>
      </table>

      <p><strong>code: chk10</strong> — 10% off this order — apply at checkout after re-adding items to cart</p>

      <p>Your lots are held for 72 hours. We ship the same or next business day after payment clears.</p>

      <p>Questions: <a href="mailto:support@anvilcompounds.shop">support@anvilcompounds.shop</a></p>
    </div>
    <?php
    return ob_get_clean();
}
